### ISSUE TITLE
Error in Ensembler crema

### ISSUE THREAD

**Issue by EmilianoMarchese** [nicoloval/NEMtropy#25]
here it follow an example code that raises the error:

import numpy as np
import networkx as nx
from NEMtropy import UndirectedGraph, matrix_generator

adj_weigh = matrix_generator.random_weighted_matrix_generator_uniform_custom_density(n=100,
                                                                                     p=0.2,
                                                                                     sym=True,
                                                                                     sup_ext=30,
                                                                                     intweights=True)

graph.solve_tool(model="crema",
                 method="newton",
                 initial_guess="random",
                 adjacency="cm_exp",
                 method_adjacency="newton")

graph.ensemble_sampler(10, cpu_n=2, output_dir="sample/")

**Comment by nicoloval** [comment]
Hi emiliano,
first of all thank you.
The issue should be fixed with last [commit](https://github.com/nicoloval/NEMtropy/commit/8df4431e949bccbcfb4338d39afeb51edec26d26).
I proceed to close the issue
