### ISSUE TITLE
Misspelled Method in .solve_tool

### ISSUE THREAD

**Issue by MarsMDK** [nicoloval/NEMtropy#36]
When using solve_tool if the method in input is "quasi-newton" an error occurs:
" ValueError: Method must be "newton","quasi-newton", or "fixed-point". "

Instead, solve_tool works if "quasinewton" is written instead of "quasi-newton".
Please uniform the method string with the warning error.

**Comment by mat701** [comment]
Thanks for the comment! We fixed the issue in 2.0.3
