### ISSUE TITLE
Incompatibility issue with bicm

### ISSUE THREAD

**Issue by skojaku** [nicoloval/NEMtropy#52]
Hi developers, thanks for the great package! I've been using this package and it worked great so far. But recently, I got an error that I've never seen, which is something to do with `bicm` package. Namely, I got the following error:

<img width="647" alt="Screenshot 2024-06-14 at 5 07 46 AM" src="https://github.com/nicoloval/NEMtropy/assets/18026375/b0f9e4a0-c863-4b5f-b2ae-3fc9f0fb9e92">

Here is the code to reproduce the results. 

```python
import bicm
from NEMtropy import UndirectedGraph
import numpy as np
import networkx as nx
from scipy import sparse

G = nx.karate_club_graph()
A = nx.adjacency_matrix(G)
A = A + A.T
A.data = np.ones_like(A.data)

graph = UndirectedGraph(A.todense())
graph.solve_tool(model="cm_exp", method="newton", initial_guess="random")
```

Checking with bicm package, I think the recent changes in bicm package would be the root of the problem, and a tentative solution would be to install a previous version of the bicm package.

**Comment by mat701** [comment]
Hi, thanks for opening the issue!

Indeed there is a problem, with the package overriding the models_functions of the undirected models with the ones of the bicm. I'll fix it in the next days, for the moment I suggest to work with the previous version (before 3.0) or directly with [the bicm package](https://github.com/mat701/BiCM) if you need bipartite models!

**Comment by mat701** [comment]
Done, upgrading your bicm version to 3.2.0 should be fine! The new 3.0.1 version of NEMtropy also requires bicm>=3.2.0 so upgrading NEMtropy should work as well.  

Note that in your code your graph should be initialised through graph = UndirectedGraph(A.toarray()) since todense() returns an incompatible numpy matrix instead of a numpy array.
